# Generated by Django 4.2 on 2024-02-07 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('none', 'None'), ('leaders', 'Leaders'), ('engineering', 'Engineering'), ('research', 'Research'), ('design', 'Design'), ('operations', 'Operations'), ('business', 'Business')], default='none', max_length=20)),
                ('statement', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='design',
            name='info',
        ),
        migrations.RemoveField(
            model_name='design',
            name='member_ptr',
        ),
        migrations.RemoveField(
            model_name='engineering',
            name='info',
        ),
        migrations.RemoveField(
            model_name='engineering',
            name='member_ptr',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='info',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='member_ptr',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='info',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='member_ptr',
        ),
        migrations.RemoveField(
            model_name='research',
            name='info',
        ),
        migrations.RemoveField(
            model_name='research',
            name='member_ptr',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.DeleteModel(
            name='Engineering',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Leader',
        ),
        migrations.DeleteModel(
            name='Operations',
        ),
        migrations.DeleteModel(
            name='Research',
        ),
    ]
