# Generated by Django 4.2 on 2024-02-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Investors',
        ),
        migrations.DeleteModel(
            name='InvestorsRelation',
        ),
    ]
