# Generated by Django 4.2 on 2024-02-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_rename_info_investors_delete_investorsrelation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investors',
            new_name='Investor',
        ),
    ]
