# Generated by Django 4.2 on 2024-02-05 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('none', 'None'), ('business', 'Business'), ('design', 'Design'), ('engineering', 'Engineering'), ('ml', 'Machine Learning'), ('leaders', 'Leaders'), ('operations', 'Operations'), ('research', 'Research')], default='none', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('apply_instructions', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='career/opportunities/')),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='career.info')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='career.info')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='career.info')),
                ('image', models.ImageField(blank=True, null=True, upload_to='career/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internships', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='career.internships')),
                ('vacancies', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='career.vacancies')),
            ],
        ),
    ]
