# Generated by Django 4.2 on 2024-02-07 19:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_internship_vacancy_remove_internships_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('info_type', models.CharField(choices=[('internship', 'Internship'), ('vacancy', 'Vacancy'), ('career', 'Career')], default='none', max_length=30)),
                ('statement', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='career/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Career',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
