# Generated by Django 4.2 on 2024-02-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_alter_info_info_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'Info'},
        ),
    ]
