# Generated by Django 4.2 on 2024-02-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_providedservice_services_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopService',
        ),
    ]
