# Generated by Django 4.2 on 2024-02-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='description',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='history_timeline',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='statement_hub',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='story',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='what_we_do',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='who_we_are',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='why_intelsense',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='topic',
            field=models.CharField(choices=[('none', 'None'), ('who_we_are', 'Who we are'), ('what_we_do', 'What we do'), ('why_intelsense', 'Why Intelsense'), ('mission', 'Mission'), ('story', 'Story')], default='none', max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='WhatWeDo',
        ),
        migrations.DeleteModel(
            name='WhoWeAre',
        ),
        migrations.DeleteModel(
            name='WhyIntelsense',
        ),
    ]
