# Generated by Django 4.2 on 2024-02-05 17:25

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured', models.CharField(choices=[('false', 'Fales'), ('true', 'True')], default='false', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('read_time', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
