# Generated by Django 4.2 on 2024-02-05 17:25

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('product_rating', models.CharField(choices=[('none', 'None'), ('top', 'Top')], default='none', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='products/logos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='products/videos/')),
                ('product_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
    ]
