# Generated by Django 4.2 on 2024-02-05 17:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopProduct',
        ),
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            bases=('products.product',),
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
    ]
