# Generated by Django 4.2 on 2024-02-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='opinions',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='organizations',
        ),
        migrations.AddField(
            model_name='partners',
            name='opinions',
            field=models.ManyToManyField(blank=True, to='partners.opinion'),
        ),
        migrations.AddField(
            model_name='partners',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='partners.organization'),
        ),
    ]
