# Generated by Django 4.2 on 2024-02-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_remove_partners_opinions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
